#:import MDScreen kivymd.uix.screen.MDScreen
#:import MDScreenManager kivymd.uix.screenmanager.MDScreenManager

MDScreenManager:
    id: screen_manager

    MainScreen:
        name: "main"

    WaitingScreen:
        name: "waiting"

    QRCodeScreen:
        name: "qr_code"
    
    ThankYouScreen:
        name: "thank_you"

    NetworkErrorScreen:
        name: "network_error"

    SettingsScreen:
        name: "settings"